title:              Can Üreten <br> Data Scientist
email:              canureten@alumni.sabanciuniv.edu
description:        Portfolio & Professional Blog
author:             Can Üreten
baseurl:            ""
url:                "https://canureten.github.io"

# Social Profiles
twitter_username:   canureten
github_username:    canureten
instagram_username: canureten
linkedin_username:  canureten

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
